replicaCount: 3

image:
  repository: "us-central1-docker.pkg.dev/terraform-project-jan24/artemis/artemis"
  tag: "2.0.0"

service:
  type: ClusterIP
  port: 5000


ingress:
  enabled: true
  annotations: {}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"

    
  hosts:
    - host: dev-artemis.overevkina.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.overevkina.com
